// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nodeagent.proto

package nodeagent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetDirectorySizeRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDirectorySizeRequest) Reset()         { *m = GetDirectorySizeRequest{} }
func (m *GetDirectorySizeRequest) String() string { return proto.CompactTextString(m) }
func (*GetDirectorySizeRequest) ProtoMessage()    {}
func (*GetDirectorySizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5331ae4b8115762, []int{0}
}

func (m *GetDirectorySizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDirectorySizeRequest.Unmarshal(m, b)
}
func (m *GetDirectorySizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDirectorySizeRequest.Marshal(b, m, deterministic)
}
func (m *GetDirectorySizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDirectorySizeRequest.Merge(m, src)
}
func (m *GetDirectorySizeRequest) XXX_Size() int {
	return xxx_messageInfo_GetDirectorySizeRequest.Size(m)
}
func (m *GetDirectorySizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDirectorySizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDirectorySizeRequest proto.InternalMessageInfo

func (m *GetDirectorySizeRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GetDirectorySizeReply struct {
	Infos                map[string]int64 `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetDirectorySizeReply) Reset()         { *m = GetDirectorySizeReply{} }
func (m *GetDirectorySizeReply) String() string { return proto.CompactTextString(m) }
func (*GetDirectorySizeReply) ProtoMessage()    {}
func (*GetDirectorySizeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5331ae4b8115762, []int{1}
}

func (m *GetDirectorySizeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDirectorySizeReply.Unmarshal(m, b)
}
func (m *GetDirectorySizeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDirectorySizeReply.Marshal(b, m, deterministic)
}
func (m *GetDirectorySizeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDirectorySizeReply.Merge(m, src)
}
func (m *GetDirectorySizeReply) XXX_Size() int {
	return xxx_messageInfo_GetDirectorySizeReply.Size(m)
}
func (m *GetDirectorySizeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDirectorySizeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetDirectorySizeReply proto.InternalMessageInfo

func (m *GetDirectorySizeReply) GetInfos() map[string]int64 {
	if m != nil {
		return m.Infos
	}
	return nil
}

type GetMountpointsSizeRequest struct {
	Paths                []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMountpointsSizeRequest) Reset()         { *m = GetMountpointsSizeRequest{} }
func (m *GetMountpointsSizeRequest) String() string { return proto.CompactTextString(m) }
func (*GetMountpointsSizeRequest) ProtoMessage()    {}
func (*GetMountpointsSizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5331ae4b8115762, []int{2}
}

func (m *GetMountpointsSizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMountpointsSizeRequest.Unmarshal(m, b)
}
func (m *GetMountpointsSizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMountpointsSizeRequest.Marshal(b, m, deterministic)
}
func (m *GetMountpointsSizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMountpointsSizeRequest.Merge(m, src)
}
func (m *GetMountpointsSizeRequest) XXX_Size() int {
	return xxx_messageInfo_GetMountpointsSizeRequest.Size(m)
}
func (m *GetMountpointsSizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMountpointsSizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMountpointsSizeRequest proto.InternalMessageInfo

func (m *GetMountpointsSizeRequest) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type GetMountpointsSizeReply struct {
	Infos                map[string]*Sizes `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetMountpointsSizeReply) Reset()         { *m = GetMountpointsSizeReply{} }
func (m *GetMountpointsSizeReply) String() string { return proto.CompactTextString(m) }
func (*GetMountpointsSizeReply) ProtoMessage()    {}
func (*GetMountpointsSizeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5331ae4b8115762, []int{3}
}

func (m *GetMountpointsSizeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMountpointsSizeReply.Unmarshal(m, b)
}
func (m *GetMountpointsSizeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMountpointsSizeReply.Marshal(b, m, deterministic)
}
func (m *GetMountpointsSizeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMountpointsSizeReply.Merge(m, src)
}
func (m *GetMountpointsSizeReply) XXX_Size() int {
	return xxx_messageInfo_GetMountpointsSizeReply.Size(m)
}
func (m *GetMountpointsSizeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMountpointsSizeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetMountpointsSizeReply proto.InternalMessageInfo

func (m *GetMountpointsSizeReply) GetInfos() map[string]*Sizes {
	if m != nil {
		return m.Infos
	}
	return nil
}

type Sizes struct {
	Tsize                int64    `protobuf:"varint,1,opt,name=Tsize,proto3" json:"Tsize,omitempty"`
	Usize                int64    `protobuf:"varint,2,opt,name=Usize,proto3" json:"Usize,omitempty"`
	Fsize                int64    `protobuf:"varint,3,opt,name=Fsize,proto3" json:"Fsize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sizes) Reset()         { *m = Sizes{} }
func (m *Sizes) String() string { return proto.CompactTextString(m) }
func (*Sizes) ProtoMessage()    {}
func (*Sizes) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5331ae4b8115762, []int{4}
}

func (m *Sizes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sizes.Unmarshal(m, b)
}
func (m *Sizes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sizes.Marshal(b, m, deterministic)
}
func (m *Sizes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sizes.Merge(m, src)
}
func (m *Sizes) XXX_Size() int {
	return xxx_messageInfo_Sizes.Size(m)
}
func (m *Sizes) XXX_DiscardUnknown() {
	xxx_messageInfo_Sizes.DiscardUnknown(m)
}

var xxx_messageInfo_Sizes proto.InternalMessageInfo

func (m *Sizes) GetTsize() int64 {
	if m != nil {
		return m.Tsize
	}
	return 0
}

func (m *Sizes) GetUsize() int64 {
	if m != nil {
		return m.Usize
	}
	return 0
}

func (m *Sizes) GetFsize() int64 {
	if m != nil {
		return m.Fsize
	}
	return 0
}

func init() {
	proto.RegisterType((*GetDirectorySizeRequest)(nil), "nodeagent.GetDirectorySizeRequest")
	proto.RegisterType((*GetDirectorySizeReply)(nil), "nodeagent.GetDirectorySizeReply")
	proto.RegisterMapType((map[string]int64)(nil), "nodeagent.GetDirectorySizeReply.InfosEntry")
	proto.RegisterType((*GetMountpointsSizeRequest)(nil), "nodeagent.GetMountpointsSizeRequest")
	proto.RegisterType((*GetMountpointsSizeReply)(nil), "nodeagent.GetMountpointsSizeReply")
	proto.RegisterMapType((map[string]*Sizes)(nil), "nodeagent.GetMountpointsSizeReply.InfosEntry")
	proto.RegisterType((*Sizes)(nil), "nodeagent.sizes")
}

func init() { proto.RegisterFile("nodeagent.proto", fileDescriptor_b5331ae4b8115762) }

var fileDescriptor_b5331ae4b8115762 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x3b, 0xcd, 0x97, 0x0f, 0x72, 0xbb, 0xb0, 0x0c, 0x15, 0x6b, 0x57, 0x61, 0x10, 0x29,
	0x48, 0x0b, 0xc6, 0x4d, 0x71, 0x57, 0xfc, 0x53, 0x2a, 0xe8, 0x62, 0xb4, 0x1b, 0x57, 0x46, 0x7b,
	0xd5, 0x60, 0x99, 0x89, 0xc9, 0x44, 0x48, 0x9f, 0xc3, 0xa7, 0xf0, 0x4d, 0x7c, 0x2b, 0x99, 0x99,
	0x6a, 0x53, 0x13, 0xcc, 0xee, 0xde, 0xc3, 0xdc, 0x39, 0xf3, 0x3b, 0x77, 0x60, 0x4b, 0xc8, 0x39,
	0x86, 0x4f, 0x28, 0xd4, 0x30, 0x4e, 0xa4, 0x92, 0xd4, 0xfb, 0x11, 0xd8, 0x00, 0x76, 0x26, 0xa8,
	0x4e, 0xa3, 0x04, 0x1f, 0x94, 0x4c, 0xf2, 0xeb, 0x68, 0x89, 0x1c, 0x5f, 0x33, 0x4c, 0x15, 0xa5,
	0xf0, 0x2f, 0x0e, 0xd5, 0x73, 0x97, 0xf8, 0xa4, 0xef, 0x71, 0x53, 0xb3, 0x77, 0x02, 0xdb, 0xe5,
	0xf3, 0xf1, 0x22, 0xa7, 0x63, 0x70, 0x23, 0xf1, 0x28, 0xd3, 0x2e, 0xf1, 0x9d, 0x7e, 0x2b, 0x38,
	0x18, 0xae, 0x4d, 0x2b, 0x07, 0x86, 0x53, 0x7d, 0xfa, 0x4c, 0xa8, 0x24, 0xe7, 0x76, 0xb2, 0x37,
	0x02, 0x58, 0x8b, 0xb4, 0x0d, 0xce, 0x0b, 0xe6, 0x2b, 0x77, 0x5d, 0xd2, 0x0e, 0xb8, 0x6f, 0xe1,
	0x22, 0xc3, 0x6e, 0xd3, 0x27, 0x7d, 0x87, 0xdb, 0xe6, 0xb8, 0x39, 0x22, 0xec, 0x10, 0x76, 0x27,
	0xa8, 0x2e, 0x65, 0x26, 0x54, 0x2c, 0x23, 0xa1, 0xd2, 0x22, 0x47, 0x07, 0x5c, 0xfd, 0x76, 0xfb,
	0x32, 0x8f, 0xdb, 0x86, 0x7d, 0x10, 0x43, 0x5e, 0x9a, 0xd1, 0x2c, 0x27, 0x9b, 0x2c, 0x83, 0x4d,
	0x96, 0xaa, 0x91, 0x0a, 0x9a, 0x8b, 0x1a, 0x9a, 0xfd, 0x22, 0x4d, 0x2b, 0x68, 0x17, 0x4c, 0xd2,
	0x68, 0x89, 0x69, 0x91, 0x6f, 0x0a, 0xae, 0xd1, 0x34, 0xcb, 0x8d, 0xae, 0xcc, 0x45, 0x0e, 0xb7,
	0x8d, 0x56, 0x67, 0x46, 0x5d, 0x05, 0x33, 0xfb, 0x56, 0xcf, 0x8d, 0xea, 0x58, 0xd5, 0x34, 0xc1,
	0x27, 0x01, 0xef, 0x4a, 0xce, 0x71, 0xac, 0x9d, 0xe8, 0x2d, 0xb4, 0x7f, 0x6f, 0x87, 0xb2, 0x3f,
	0x57, 0x67, 0x32, 0xed, 0xf9, 0x75, 0xeb, 0x65, 0x0d, 0x7a, 0x07, 0xb4, 0x9c, 0x16, 0xdd, 0xab,
	0x09, 0xd3, 0xde, 0xcf, 0xea, 0x23, 0x67, 0x8d, 0xfb, 0xff, 0xe6, 0x3b, 0x1f, 0x7d, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x7d, 0x16, 0xe8, 0x90, 0xe1, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeAgentClient is the client API for NodeAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeAgentClient interface {
	GetDirectorySize(ctx context.Context, in *GetDirectorySizeRequest, opts ...grpc.CallOption) (*GetDirectorySizeReply, error)
	GetMountpointsSize(ctx context.Context, in *GetMountpointsSizeRequest, opts ...grpc.CallOption) (*GetMountpointsSizeReply, error)
}

type nodeAgentClient struct {
	cc *grpc.ClientConn
}

func NewNodeAgentClient(cc *grpc.ClientConn) NodeAgentClient {
	return &nodeAgentClient{cc}
}

func (c *nodeAgentClient) GetDirectorySize(ctx context.Context, in *GetDirectorySizeRequest, opts ...grpc.CallOption) (*GetDirectorySizeReply, error) {
	out := new(GetDirectorySizeReply)
	err := c.cc.Invoke(ctx, "/nodeagent.NodeAgent/GetDirectorySize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetMountpointsSize(ctx context.Context, in *GetMountpointsSizeRequest, opts ...grpc.CallOption) (*GetMountpointsSizeReply, error) {
	out := new(GetMountpointsSizeReply)
	err := c.cc.Invoke(ctx, "/nodeagent.NodeAgent/GetMountpointsSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAgentServer is the server API for NodeAgent service.
type NodeAgentServer interface {
	GetDirectorySize(context.Context, *GetDirectorySizeRequest) (*GetDirectorySizeReply, error)
	GetMountpointsSize(context.Context, *GetMountpointsSizeRequest) (*GetMountpointsSizeReply, error)
}

// UnimplementedNodeAgentServer can be embedded to have forward compatible implementations.
type UnimplementedNodeAgentServer struct {
}

func (*UnimplementedNodeAgentServer) GetDirectorySize(ctx context.Context, req *GetDirectorySizeRequest) (*GetDirectorySizeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirectorySize not implemented")
}
func (*UnimplementedNodeAgentServer) GetMountpointsSize(ctx context.Context, req *GetMountpointsSizeRequest) (*GetMountpointsSizeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMountpointsSize not implemented")
}

func RegisterNodeAgentServer(s *grpc.Server, srv NodeAgentServer) {
	s.RegisterService(&_NodeAgent_serviceDesc, srv)
}

func _NodeAgent_GetDirectorySize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDirectorySizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetDirectorySize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeagent.NodeAgent/GetDirectorySize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetDirectorySize(ctx, req.(*GetDirectorySizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetMountpointsSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMountpointsSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetMountpointsSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeagent.NodeAgent/GetMountpointsSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetMountpointsSize(ctx, req.(*GetMountpointsSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nodeagent.NodeAgent",
	HandlerType: (*NodeAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDirectorySize",
			Handler:    _NodeAgent_GetDirectorySize_Handler,
		},
		{
			MethodName: "GetMountpointsSize",
			Handler:    _NodeAgent_GetMountpointsSize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodeagent.proto",
}
